version: '3'
networks:
    camino:
volumes:
  ipcs:
    name: ipcs
  mysql-data:
    name: mysql-data
services:
  index-node:
    container_name: index-node
    image: c4tplatform/caminogo:v0.1.0
    command: [/files/start-node.sh]
    ports:
        - '9661:9650'
    networks:
        - camino
    volumes:
        - ./files:/files
        - ipcs:/tmp
    depends_on:
        - indexer
    resources:
      limits:
        memory: 1G
  indexer: &ortelius-app
    image: "avaplatform/ortelius:v1.7.10"
    command: ["stream", "indexer", "-c", "/opt/config.json"]
    networks:
      - camino
    volumes:
      - ipcs:/tmp
      - ./ortelius/config.standalone.json:/opt/config.json
    restart: on-failure
    depends_on:
      - mysql
    resources:
      limits:
        memory: 1G
  api:
    <<: *ortelius-app
    command: ["api", "-c", "/opt/config.json"]
    ports:
      - 8080:8080
  mysql:
    image: "mysql:8.0.26"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ortelius
    restart: on-failure
    resources:
      limits:
        memory: 1G
  migrate:
    image: "migrate/migrate:v4.14.1"
    volumes:
      - ./migrations:/migrations
    depends_on:
      - mysql
    entrypoint: ["/bin/sh"]
    command: |
      -c 'while ! migrate -path=/migrations/ -database "mysql://root:password@tcp(mysql:3306)/ortelius" up; do
        sleep 1
      done'
    restart: on-failure
