version: '3'
networks:
    camino:
volumes:
  ipcs:
    name: ipcs
  mysql-data:
    name: mysql-data
services:
  index-node:
    container_name: index-node
    image: c4tplatform/caminogo:v0.1.0
    command: [/files/start-node.sh]
    ports:
        - '9661:9650'
    networks:
        - camino
    volumes:
        - ./files:/files
        - ipcs:/tmp
    depends_on:
        - indexer-api
    deploy:
      resources:
        limits:
          memory: 1G
  indexer-api: &ortelius-app
    image: "c4tplatform/magellan:v0.0.2"
    command: ["stream", "indexer", "api", "-c", "/opt/config.json"]
    networks:
      - camino
    volumes:
      - ipcs:/tmp
      - ./ortelius/config.standalone.json:/opt/config.json
    restart: on-failure
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - 8080:8080
  mysql:
    image: "mysql:8.0.26"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ortelius
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1G
    cap_add:
      - SYS_NICE
  migrate:
    image: "migrate/migrate:v4.14.1"
    volumes:
      - ./migrations:/migrations
    depends_on:
      - mysql
    entrypoint: ["/bin/sh"]
    command: |
      -c 'while ! migrate -path=/migrations/ -database "mysql://root:password@tcp(mysql:3306)/ortelius" up; do
        sleep 1
      done'
    restart: on-failure
