version: '3'
networks:
    camino:
volumes:
  mysql-data:
    name: mysql-data
services:
  indexer-api: &ortelius-app
    image: "c4tplatform/magellan:v0.0.3"
    command: ["stream", "indexer", "api", "-c", "/opt/config.json"]
    networks:
      - camino
    volumes:
      - /tmp:/tmp
      - ./ortelius/config.standalone.json:/opt/config.json
    restart: always
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - 8080:8080
  mysql:
    image: "mysql:8.0.26"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ortelius
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
    cap_add:
      - SYS_NICE
  migrate:
    image: "migrate/migrate:v4.14.1"
    volumes:
      - ./migrations:/migrations
    depends_on:
      - mysql
    entrypoint: ["/bin/sh"]
    command: |
      -c 'while ! migrate -path=/migrations/ -database "mysql://root:password@tcp(mysql:3306)/ortelius" up; do
        sleep 1
      done'
    restart: on-failure
